# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 582)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(390, 20, 371, 511))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"    background:white;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 291, 281))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.file_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.list_1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.list_1.setContentsMargins(0, 0, 0, 0)
        self.list_1.setObjectName("list_1")
        self.open_file = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.open_file.setFont(font)
        self.open_file.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.open_file.setObjectName("open_file")
        self.list_1.addWidget(self.open_file, 2, 1, 1, 1)
        self.new_file_entry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.new_file_entry.setFont(font)
        self.new_file_entry.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"")
        self.new_file_entry.setObjectName("new_file_entry")
        self.list_1.addWidget(self.new_file_entry, 0, 0, 1, 1)
        self.new_sheet_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.new_sheet_2.setFont(font)
        self.new_sheet_2.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.new_sheet_2.setObjectName("new_sheet_2")
        self.list_1.addWidget(self.new_sheet_2, 1, 1, 1, 1)
        self.new_sheet_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.new_sheet_3.setFont(font)
        self.new_sheet_3.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"")
        self.new_sheet_3.setObjectName("new_sheet_3")
        self.list_1.addWidget(self.new_sheet_3, 1, 0, 1, 1)
        self.open_file_entry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.open_file_entry.setFont(font)
        self.open_file_entry.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"")
        self.open_file_entry.setObjectName("open_file_entry")
        self.list_1.addWidget(self.open_file_entry, 2, 0, 1, 1)
        self.new_file_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.new_file_2.setFont(font)
        self.new_file_2.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"\n"
"\n"
"")
        self.new_file_2.setObjectName("new_file_2")
        self.list_1.addWidget(self.new_file_2, 0, 1, 1, 1)
        self.list_1.setColumnStretch(0, 1)
        self.tabWidget.addTab(self.file_tab, "")
        self.edit_tab = QtWidgets.QWidget()
        self.edit_tab.setObjectName("edit_tab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.edit_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 271, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.list_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.list_3.setContentsMargins(0, 0, 0, 0)
        self.list_3.setObjectName("list_3")
        self.nums_1 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.nums_1.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.nums_1.setObjectName("nums_1")
        self.list_3.addWidget(self.nums_1, 1, 0, 1, 2)
        self.all_num = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.all_num.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.all_num.setObjectName("all_num")
        self.list_3.addWidget(self.all_num, 2, 0, 1, 1)
        self.banj = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.banj.setFont(font)
        self.banj.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.banj.setObjectName("banj")
        self.list_3.addWidget(self.banj, 3, 0, 1, 1)
        self.num_edit = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.num_edit.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.num_edit.setObjectName("num_edit")
        self.list_3.addWidget(self.num_edit, 2, 1, 1, 1)
        self.banje = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.banje.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"")
        self.banje.setObjectName("banje")
        self.list_3.addWidget(self.banje, 3, 1, 1, 1)
        self.str_is = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.str_is.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"")
        self.str_is.setObjectName("str_is")
        self.list_3.addWidget(self.str_is, 0, 0, 1, 1)
        self.str_start = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.str_start.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.str_start.setObjectName("str_start")
        self.list_3.addWidget(self.str_start, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.list_3.addWidget(self.pushButton_4, 5, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.list_3.addWidget(self.pushButton_3, 4, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.list_3.addWidget(self.lineEdit, 5, 1, 1, 1)
        self.list_3.setColumnStretch(0, 1)
        self.list_3.setColumnStretch(1, 1)
        self.tabWidget.addTab(self.edit_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.dial = QtWidgets.QDial(self.tab)
        self.dial.setGeometry(QtCore.QRect(0, 180, 50, 64))
        self.dial.setStyleSheet("background: rgb(0,205,205);\n"
"\n"
"\n"
"")
        self.dial.setObjectName("dial")
        self.labelC = QtWidgets.QLabel(self.tab)
        self.labelC.setGeometry(QtCore.QRect(60, 190, 151, 21))
        self.labelC.setText("")
        self.labelC.setObjectName("labelC")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 220, 75, 23))
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(80, 20, 81, 71))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.file = QtWidgets.QListWidget(self.centralwidget)
        self.file.setGeometry(QtCore.QRect(10, 320, 191, 211))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.file.setFont(font)
        self.file.setStyleSheet("\n"
"   border-style:solid;\n"
"    border-width:0pz 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"")
        self.file.setObjectName("file")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 350, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 450, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.open_text = QtWidgets.QLabel(self.centralwidget)
        self.open_text.setGeometry(QtCore.QRect(200, 310, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.open_text.setFont(font)
        self.open_text.setAlignment(QtCore.Qt.AlignCenter)
        self.open_text.setObjectName("open_text")
        self.logoff = QtWidgets.QPushButton(self.centralwidget)
        self.logoff.setGeometry(QtCore.QRect(230, 410, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setBold(False)
        font.setWeight(50)
        self.logoff.setFont(font)
        self.logoff.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.logoff.setObjectName("logoff")
        self.resetpwd = QtWidgets.QPushButton(self.centralwidget)
        self.resetpwd.setGeometry(QtCore.QRect(230, 490, 121, 31))
        self.resetpwd.setStyleSheet("QPushButton\n"
"{\n"
"   \n"
"   border-style:solid;\n"
"    border-width:0pz 0px 5px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"   border-style:solid;\n"
"    border-width:0px 0px 2px 0px;\n"
"    border-color:rgb(0, 205, 205);\n"
"}\n"
"    \n"
"")
        self.resetpwd.setObjectName("resetpwd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.new_file = QtWidgets.QAction(MainWindow)
        self.new_file.setObjectName("new_file")
        self.new_sheet = QtWidgets.QAction(MainWindow)
        self.new_sheet.setObjectName("new_sheet")
        self.in_file = QtWidgets.QAction(MainWindow)
        self.in_file.setObjectName("in_file")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.new_sheet_3)
        MainWindow.setTabOrder(self.new_sheet_3, self.new_sheet_2)
        MainWindow.setTabOrder(self.new_sheet_2, self.open_file)
        MainWindow.setTabOrder(self.open_file, self.open_file_entry)
        MainWindow.setTabOrder(self.open_file_entry, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.new_file_2)
        MainWindow.setTabOrder(self.new_file_2, self.new_file_entry)
        MainWindow.setTabOrder(self.new_file_entry, self.file)
        MainWindow.setTabOrder(self.file, self.num_edit)
        MainWindow.setTabOrder(self.num_edit, self.str_start)
        MainWindow.setTabOrder(self.str_start, self.str_is)
        MainWindow.setTabOrder(self.str_is, self.nums_1)
        MainWindow.setTabOrder(self.nums_1, self.all_num)
        MainWindow.setTabOrder(self.all_num, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.banj)
        MainWindow.setTabOrder(self.banj, self.banje)
        MainWindow.setTabOrder(self.banje, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.dial)
        MainWindow.setTabOrder(self.dial, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.logoff)
        MainWindow.setTabOrder(self.logoff, self.resetpwd)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "号数"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "成绩"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "等级"))
        self.open_file.setText(_translate("MainWindow", "打开班级"))
        self.new_sheet_2.setText(_translate("MainWindow", "创建考试"))
        self.new_file_2.setText(_translate("MainWindow", "创建班级"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.file_tab), _translate("MainWindow", "文件"))
        self.nums_1.setText(_translate("MainWindow", "计算平均分"))
        self.all_num.setText(_translate("MainWindow", "计算总分"))
        self.banj.setText(_translate("MainWindow", "年段排名"))
        self.num_edit.setText(_translate("MainWindow", "修改分数"))
        self.str_start.setText(_translate("MainWindow", "筛选分数"))
        self.pushButton_4.setText(_translate("MainWindow", "查询成绩"))
        self.pushButton_3.setText(_translate("MainWindow", "班级排名"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.edit_tab), _translate("MainWindow", "操作"))
        self.label_2.setText(_translate("MainWindow", "BANJ-SOUCE"))
        self.label_3.setText(_translate("MainWindow", "V3.3 (Theme Upgrade)"))
        self.label_4.setText(_translate("MainWindow", "POWERED BY AERO8M"))
        self.pushButton_5.setText(_translate("MainWindow", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "关于"))
        self.label.setText(_translate("MainWindow", "0 班级"))
        self.pushButton_2.setText(_translate("MainWindow", "打开文件夹"))
        self.open_text.setText(_translate("MainWindow", "未打开"))
        self.logoff.setText(_translate("MainWindow", "注销"))
        self.resetpwd.setText(_translate("MainWindow", "重置密码"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.new_file.setText(_translate("MainWindow", "新建班级"))
        self.new_sheet.setText(_translate("MainWindow", "新建考试"))
        self.in_file.setText(_translate("MainWindow", "导入班级"))
        self.action_2.setText(_translate("MainWindow", "全科平均分"))
        self.action_3.setText(_translate("MainWindow", "单科平均分"))
        self.action_4.setText(_translate("MainWindow", "计算总分"))
